package login;

import database.databaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Login model
 *
 * @author Daniel Zawadzki, s9482
 * @version 1.0
 */
public class LoginModel {

    // SQL connection object
    Connection connection;

    /**
     * Constructor
     */
    public LoginModel() {
        try {
            this.connection = databaseConnection.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        if (this.connection == null) {
            System.exit(1);
        }
    }

    /**
     * Checker to database connection
     *
     * @return connection status
     */
    public boolean checkDatabaseConnection() {
        return this.connection != null;
    }


    /**
     * Authenticate user basing on passed email address and password
     *
     * @param emailAddress
     * @param password
     * @return
     * @throws Exception
     */
    public List<String> authenticate(String emailAddress, String password) throws Exception {

        // An object that represents a precompiled SQL statement.
        PreparedStatement pr = null;

        // A table of data representing a database result set generated by executing a statement that queries the database.
        ResultSet rs = null;
        ResultSetMetaData rsmd = null;
        int columnsNumber = 0;

        // SQL statement
        String sql = "SELECT * FROM users WHERE emailAddress = ? and password = ?";

        try {
            pr = connection.prepareStatement(sql);
            pr.setString(1, emailAddress);
            pr.setString(2, password);
            rs = pr.executeQuery();
            rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();


            if (rs.next()) {

                // Print db columns connected to authenticated user.
                System.out.println("Logged user info\n" +
                        "============================");
                List<String> user = new ArrayList<String>();
                for (int i = 1; i <= columnsNumber; i++) {
                    user.add(rs.getString(i));
                    System.out.println(rsmd.getColumnName(i) + ": " + rs.getString(i));
                }

                return user;

            } else {
                System.out.println("Incorrect credentials.");
                return null;
            }
        } catch (SQLException se) {
            return null;
        } finally {
            pr.close();
            rs.close();
        }
    }
}
